Customer:

    AMPQ_URL:                           "amqp://localhost"
    
    AMPQ_HOST:                          "localhost"
    AMPQ_AMPQ_PORT:                     5672
    AMPQ_USER:                          "guest"
    AMPQ_PASSWORD:                      "guest"
    
    AMPQ_RECONNECT:                     true
    AMPQ_RECONNECT_STRATEGY:            "linear"
    AMPQ_BACKOFF_TIME:                  1000
    
    RABBITMQ_QUEUE:                     "MAIL_CHANNEL"
    
    CRON_JOB_PATTERN:                   "0 0 */4 * * *"          
    CRON_JOB_TIMEZONE:                  "Asia/Tehran"

    MONGODB_STRING:                     "mongodb://localhost/eventum"
    
    HEADER_FROM:                        "From: Eventum.ir <events@eventum.ir>"
    HEADER_RETURN_PATH:                 "Return-Path: events@eventum.ir"
    EMAIL_SUBJECT:                      "دعوت به اطلاع رسانی رویداد شما"
    
    TIME_THRESHOLD:                     604800000