Customer:

    AMPQ_URL:                           "amqp://localhost"
    AMPQ_RECONNECT:                     true
    AMPQ_RECONNECT_STRATEGY:            "linear"
    AMPQ_BACKOFF_TIME:                  1000
    
    RABBITMQ_QUEUE:                     ""
